import { describe, it, expect, beforeAll } from "bun:test";
import { readFile } from "fs/promises";
import { join } from "path";
import { existsSync } from "fs";

// .claude-plugin/marketplace.json is generated by `bun run compile` (which CI
// runs before tests). It is the explicit allowlist external ecosystems read —
// secret/hidden/zombie skills must never appear in it.

const MARKETPLACE_PATH = join(process.cwd(), ".claude-plugin", "marketplace.json");

let marketplace: {
  name: string;
  owner: { name: string };
  plugins: { name: string; source: string; strict: boolean; skills: string[] }[];
};

beforeAll(async () => {
  marketplace = JSON.parse(await readFile(MARKETPLACE_PATH, "utf-8"));
});

describe("marketplace.json", () => {
  it("exists and has the expected top-level shape", () => {
    expect(marketplace.name).toBe("oracle-skills");
    expect(marketplace.owner.name).toBeTruthy();
    expect(marketplace.plugins).toHaveLength(1);
    expect(marketplace.plugins[0].strict).toBe(false);
  });

  it("never lists secret skills", () => {
    const listed = marketplace.plugins[0].skills.join("\n");
    expect(listed).not.toContain("release-alpha");
    expect(listed).not.toContain("release-beta");
  });

  it("never lists archived (zombie) skills", () => {
    for (const path of marketplace.plugins[0].skills) {
      expect(path).not.toContain("/.archive/");
    }
  });

  it("every listed skill path exists with a SKILL.md", () => {
    for (const path of marketplace.plugins[0].skills) {
      expect(existsSync(join(process.cwd(), path, "SKILL.md"))).toBe(true);
    }
  });

  it("skill paths are sorted for stable diffs", () => {
    const paths = marketplace.plugins[0].skills;
    expect(paths).toEqual([...paths].sort((a, b) => a.localeCompare(b)));
  });

  it("lists a sane number of curated skills", () => {
    // 35 active skills minus 2 secret (release-alpha, release-beta) = 33 today.
    // Bound loosely so adding/removing a skill doesn't break this test.
    const n = marketplace.plugins[0].skills.length;
    expect(n).toBeGreaterThan(20);
    expect(n).toBeLessThan(60);
  });
});
